import { PATHS } from "./paths";
import { CONFIG } from "./config";

export const ENDPOINTS = {
	LOGIN: CONFIG.BASE_URL + PATHS.LOGIN,
	USER: CONFIG.BASE_URL + PATHS.USER,
	ASSIGNMENT: CONFIG.BASE_URL + PATHS.ASSIGNMENT,
	ASSET: CONFIG.BASE_URL + PATHS.ASSET,
	RETURN: CONFIG.BASE_URL + PATHS.RETURN,
	REPORT: CONFIG.BASE_URL + PATHS.REPORT,
	CATEGORY: CONFIG.BASE_URL + PATHS.CATEGORY,
	CHANGE_PASSWORD: CONFIG.BASE_URL + PATHS.CHANGE_PASSWORD
};
